name: pull request

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  pull_request_based:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notification for synchronize of PR..
      run: |
        echo "Some of the pull requests have been synchronized"
