name: manually running

on:
  workflow_dispatch:

jobs:
  pull_request_based:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: long running file..
      sleep 120
      run: |
        echo "it will run for 2 min"
