name: manually running

on:
  workflow_dispatch:

jobs:
  long running file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: long running file..
      run: |
        sleep 120
        echo "it will run for 2 min"
