name: pull request

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notification for creation of PR..
      run: |
        echo "A new pull request has been created or opend"
